"""Independent re-measure of a frozen deck dir, and the signature it earns.

Rule 7 (designer != verifier): nothing here reads a number out of the committed scorecard and
believes it.  For each `frozen:` dir the script

1. rebuilds EVERY bench from that dir's own `design.json` through `ldo.dut.Design` and asserts
   the generated bytes equal the committed `*.spice` (the deck is the definition);
2. re-derives `decks.sha256` from those bytes and asserts it equals the committed digest file
   the scorecard's `raw_sha` names;
3. simulates all of them through the frozen path (`ldo.sim.run` + `ldo.metrics.promote`) and
   compares every scorecard column to the committed value;
4. re-derives the whole `provenance` block with `spicexplorer_harness.provenance()` over ITS OWN
   measured card and compares it, key by key, to the committed one -- equal `computation_hash`
   means identical scorer bytes, identical deck bytes and identical numbers;
5. only then appends ONE `evidence="signed"` ledger row per dir, carrying the verifier's own
   values and the re-derived hash block.

Any mismatch prints the delta and exits non-zero without signing.

    python verify_decks.py [--sign] [decks/reference decks/candidate]
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

# this file lives at layout/<cell>/verify/, so the repo root is three levels up
REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from spicexplorer_harness import hashes, log_run, provenance, violations  # noqa: E402

from ldo import config as C  # noqa: E402
from ldo import metrics as M  # noqa: E402
from ldo.dut import Design  # noqa: E402
from spicexplorer_harness.verify import compare_card, provenance_diff  # noqa: E402

AUTHOR = "ldo-design-agent"
VERIFIER = "signoff-verifier"
# The comparison and the provenance diff are `spicexplorer_harness.verify`, so a pass here is a
# pass in the harness's own scorecard-recompute lint: it compares at the same 1e-9 relative.


def verify(rel_dir: str, sign: bool) -> int:
    d = REPO / rel_dir
    doc = json.loads((d / "scorecard.json").read_text())
    design = Design.from_dict(json.loads((d / "design.json").read_text()))
    tag = doc["tag"]
    print(f"\n=== {rel_dir}  tag={tag}  circuit={design.circuit}  corner={design.corner} ===")

    # 1. the decks, rebuilt
    built = {b: design.deck(b) for b in design.benches()}
    bad = []
    for b, text in sorted(built.items()):
        p = d / f"{b}.spice"
        if not p.is_file():
            bad.append(f"{b}.spice missing")
        elif p.read_text() != text:
            bad.append(f"{b}.spice differs from the rebuild")
    print(f"  decks rebuilt from design.json: {len(built)}; byte mismatches: {bad or 'none'}")
    if bad:
        return 1

    # 2. the digest the provenance block names
    digest = "".join(f"{hashes.sha256_text(t)}  {b}.spice\n" for b, t in sorted(built.items()))
    committed_digest = (d / "decks.sha256").read_text()
    ok_digest = digest == committed_digest
    print(f"  decks.sha256 re-derives: {ok_digest}")
    if not ok_digest:
        return 1

    # 3. simulate
    values, records = M.run_decks(built, tag)
    statuses = {b: r["status"] for b, r in records.items()}
    not_ok = [b for b, s in statuses.items() if s != "ok"]
    nan = sorted(k for k, v in values.items() if isinstance(v, float) and math.isnan(v))
    print(f"  benches: {len(statuses)}  not ok: {not_ok or 'none'}  NaN metrics: {nan or 'none'}")
    if not_ok or nan:
        return 1

    card = {k: v for k, v in values.items() if isinstance(v, float) and not math.isnan(v)}
    ref_card = doc["scorecard"]
    cmp = compare_card(ref_card, card, rel_diag=0.0)   # a certified deck reproduces exactly
    deltas = cmp.within_resolution + cmp.outside
    print(f"  scorecard {cmp.report()}  extra measured: {cmp.extra_measured or 'none'}")

    # 4. the provenance block, re-derived over MY card
    prov = provenance(C.H, tag, card, corner=design.corner, script=M.SCRIPT,
                      raw=(d / "decks.sha256").relative_to(C.H.root).as_posix())
    prov_diff = provenance_diff(doc["provenance"], prov)
    print(f"  provenance block re-derives: {not prov_diff}"
          + (f"  differing keys: {prov_diff}" if prov_diff else ""))

    viol = violations(C.H.spec, values)
    print(f"  spec violations: {viol or 'none'}")

    if deltas or prov_diff:
        print("  VERDICT: REFUSED — the committed scorecard is not what this checkout measures")
        return 1
    print("  VERDICT: reproduced to the digit")

    if sign:
        row = log_run(C.H, tag, values, corner=design.corner,
                      deck="".join(built[b] for b in design.benches()),
                      violations=viol, design=design.as_dict(),
                      evidence="signed", author=AUTHOR, verified_by=VERIFIER,
                      extra={"benches": statuses},
                      **{k: prov[k] for k in hashes.HASH_KEYS})
        print(f"  SIGNED: ledger row {row['t']} tag={row['tag']} corner={row['corner']!r} "
              f"exp={row['exp']!r} verified_by={row['verified_by']}")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("dirs", nargs="*", default=None)
    ap.add_argument("--sign", action="store_true")
    a = ap.parse_args()
    targets = a.dirs or list(C.H.frozen)
    rc = 0
    for t in targets:
        rc |= verify(t, a.sign)
    sys.exit(rc)
